sudo: required
language: csharp

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

before_install:
  - dotnet restore

  - dotnet test .\dotnetCoreFull\dotnetCoreFull.Test.NUnit\

install:
  
  # Restore dependencies
  - dotnet restore
  # Build projects
  #- dotnet build -c $CONFIGURATION -f netcoreapp1.0 ./test/dotnetCoreFull.Test.NUnit.test.runner
  - msbuild "dotnetCoreFull\dotnetCoreFull.sln" /verbosity:minimal
#script:
  # Run tests
  #- dotnet run -c $CONFIGURATION -f netcoreapp1.0 -p ./test/dotnetCoreFull.Test.NUnit.test.runner
