version: 3.3.0.{build}
os: Visual Studio 2015
configuration: Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

before_build:
  - ps: .\scripts\show-dotnet-info.ps1
  - ps: .\scripts\set-version.ps1
  - cmd: dotnet --info
  - cmd: dotnet restore

build_script:
  - cmd: dotnet build -c Release test\dotnetCoreFull.Test.NUnit\

test_script:
  - cmd: dotnet run -c Release -p test\dotnetCoreFull.Test.NUnit\

after_test:
  - cmd: dotnet pack -c Release src\dotnetCoreFull.Test.NUnit\

test: off

artifacts:
  path: 'src\dotnetCoreFull\bin\Release\*.nupkg'
